### GET all laptops
GET http://localhost:3000/laptop

### GET single laptop
GET http://localhost:3000/laptops/6833426862a67ec55678f879

### Create laptop
POST http://localhost:3000/laptops HTTP/1.1
content-type: application/json

{   
    "manufacturer": "Acer",
    "model": "Predator Neo",
    "price": "$1,764",
    "display": "2560x1600 IPS 165Hz",
    "graphicsCard": "NVIDIA GeForce RTX 4050"
}

### Update laptop
PUT http://localhost:3000/laptops/6833426862a67ec55678f879 HTTP/1.1
content-type: application/json

{   
    "manufacturer": "Lenovo",
    "model": "Legion 5i",
    "price": "$2,243",
    "display": "2560x1600 IPS 165Hz Anti-Glare",
    "graphicsCard": "NVIDIA GeForce RTX 4070"
}

### Delete laptop
DELETE http://localhost:3000/laptops/68363838945a5abba063e10b HTTP/1.1
content-type: application/json


### GET All laptops (Render)
GET https://project1-q35a.onrender.com/laptops/

### GET single laptop (Render)
GET https://project1-q35a.onrender.com/laptops/6833426862a67ec55678f879

--------------------------------------------------------------------------------------------------------

### GET all vehicles
GET http://localhost:3000/vehicles

### GET single vehicle
GET http://localhost:3000/vehicles/68333ac862a67ec55678f86f

### Create vehicle
POST http://localhost:3000/vehicles HTTP/1.1
content-type: application/json

{    
    "manufacturer": "Nissan",
    "model": "Nismo Z",
    "modelYear": "2025",
    "color": "Cherry Red",
    "price": "$44,110"
}

### Update vehicle
PUT http://localhost:3000/vehicles/68333ac862a67ec55678f86f HTTP/1.1
content-type: application/json

{    
    "manufacturer": "Audi",
    "model": "RS6",
    "modelYear": "2025",
    "color": "Glacier White",
    "price": "$159,695"
}

### Delete vehicle
DELETE http://localhost:3000/vehicles/68333ac862a67ec55678f86f


### GET All vehicles (Render)
GET https://project1-q35a.onrender.com/vehicles/

### GET single vehicle (Render)
GET https://project1-q35a.onrender.com/vehicles/68333ac862a67ec55678f86f